"""initial schema

Revision ID: efe6fdc87b1e
Revises:
Create Date: 2026-06-09 22:03:36.259778
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "efe6fdc87b1e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sa.Enum("FREE", "PREMIUM", "MODERATOR", "ADMIN", name="userrole"), nullable=False),
        sa.Column(
            "subscription_status",
            sa.Enum("FREE", "PREMIUM", "CANCELLED", "EXPIRED", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ACTIVE", "RESTRICTED", "BANNED", name="userstatus"), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("age_confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("age_confirmation_ip", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "accounttoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounttoken_expires_at"), "accounttoken", ["expires_at"], unique=False)
    op.create_index(op.f("ix_accounttoken_purpose"), "accounttoken", ["purpose"], unique=False)
    op.create_index(op.f("ix_accounttoken_token_hash"), "accounttoken", ["token_hash"], unique=True)
    op.create_index(op.f("ix_accounttoken_used_at"), "accounttoken", ["used_at"], unique=False)
    op.create_index(op.f("ix_accounttoken_user_id"), "accounttoken", ["user_id"], unique=False)
    op.create_table(
        "auditlog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("entity_id", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auditlog_action"), "auditlog", ["action"], unique=False)
    op.create_index(op.f("ix_auditlog_actor_user_id"), "auditlog", ["actor_user_id"], unique=False)
    op.create_index(op.f("ix_auditlog_created_at"), "auditlog", ["created_at"], unique=False)
    op.create_index(op.f("ix_auditlog_entity_id"), "auditlog", ["entity_id"], unique=False)
    op.create_index(op.f("ix_auditlog_entity_type"), "auditlog", ["entity_type"], unique=False)
    op.create_table(
        "conversation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_a_id", sa.Uuid(), nullable=False),
        sa.Column("user_b_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "BLOCKED", "REPORTED", name="conversationstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_a_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_b_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conversation_status"), "conversation", ["status"], unique=False)
    op.create_index(op.f("ix_conversation_user_a_id"), "conversation", ["user_a_id"], unique=False)
    op.create_index(op.f("ix_conversation_user_b_id"), "conversation", ["user_b_id"], unique=False)
    op.create_table(
        "mediapost",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=160), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1500), nullable=True),
        sa.Column("status", sa.Enum("PUBLISHED", "HIDDEN", "REMOVED", name="poststatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("removed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mediapost_created_at"), "mediapost", ["created_at"], unique=False)
    op.create_index(op.f("ix_mediapost_status"), "mediapost", ["status"], unique=False)
    op.create_index(op.f("ix_mediapost_user_id"), "mediapost", ["user_id"], unique=False)
    op.create_table(
        "profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("location_label", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("gender", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("age_label", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=True),
        sa.Column("avatar_media_id", sa.Uuid(), nullable=True),
        sa.Column("banner_media_id", sa.Uuid(), nullable=True),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profile_slug"), "profile", ["slug"], unique=True)
    op.create_index(op.f("ix_profile_user_id"), "profile", ["user_id"], unique=True)
    op.create_table(
        "profileview",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("viewer_user_id", sa.Uuid(), nullable=False),
        sa.Column("viewed_user_id", sa.Uuid(), nullable=False),
        sa.Column("viewed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["viewed_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["viewer_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profileview_viewed_at"), "profileview", ["viewed_at"], unique=False)
    op.create_index(op.f("ix_profileview_viewed_user_id"), "profileview", ["viewed_user_id"], unique=False)
    op.create_index(op.f("ix_profileview_viewer_user_id"), "profileview", ["viewer_user_id"], unique=False)
    op.create_table(
        "report",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reporter_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum("PROFILE", "POST", "CONVERSATION", "MESSAGE", name="reporttargettype"),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "FAKE_ACCOUNT",
                "NO_CONSENT",
                "UNDERAGE",
                "PROHIBITED",
                "SPAM_OR_SCAM",
                "HARASSMENT",
                "COPYRIGHT",
                "OTHER",
                name="reportreason",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("status", sa.Enum("OPEN", "RESOLVED", "DISMISSED", name="reportstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reporter_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_created_at"), "report", ["created_at"], unique=False)
    op.create_index(op.f("ix_report_reason"), "report", ["reason"], unique=False)
    op.create_index(op.f("ix_report_reporter_user_id"), "report", ["reporter_user_id"], unique=False)
    op.create_index(op.f("ix_report_status"), "report", ["status"], unique=False)
    op.create_index(op.f("ix_report_target_id"), "report", ["target_id"], unique=False)
    op.create_index(op.f("ix_report_target_type"), "report", ["target_type"], unique=False)
    op.create_table(
        "usersession",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usersession_expires_at"), "usersession", ["expires_at"], unique=False)
    op.create_index(op.f("ix_usersession_revoked_at"), "usersession", ["revoked_at"], unique=False)
    op.create_index(op.f("ix_usersession_user_id"), "usersession", ["user_id"], unique=False)
    op.create_index(op.f("ix_usersession_value"), "usersession", ["value"], unique=True)
    op.create_table(
        "consentconfirmation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("confirms_age", sa.Boolean(), nullable=False),
        sa.Column("confirms_rights", sa.Boolean(), nullable=False),
        sa.Column("confirms_no_minors", sa.Boolean(), nullable=False),
        sa.Column("confirms_permission", sa.Boolean(), nullable=False),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["mediapost.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consentconfirmation_post_id"), "consentconfirmation", ["post_id"], unique=False)
    op.create_index(op.f("ix_consentconfirmation_user_id"), "consentconfirmation", ["user_id"], unique=False)
    op.create_table(
        "mediaasset",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preview_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mime_type", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["mediapost.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mediaasset_checksum"), "mediaasset", ["checksum"], unique=False)
    op.create_index(op.f("ix_mediaasset_post_id"), "mediaasset", ["post_id"], unique=False)
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sender_id", sa.Uuid(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("status", sa.Enum("SENT", "READ", "REMOVED", name="messagestatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_conversation_id"), "message", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_message_created_at"), "message", ["created_at"], unique=False)
    op.create_index(op.f("ix_message_sender_id"), "message", ["sender_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_sender_id"), table_name="message")
    op.drop_index(op.f("ix_message_created_at"), table_name="message")
    op.drop_index(op.f("ix_message_conversation_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_mediaasset_post_id"), table_name="mediaasset")
    op.drop_index(op.f("ix_mediaasset_checksum"), table_name="mediaasset")
    op.drop_table("mediaasset")
    op.drop_index(op.f("ix_consentconfirmation_user_id"), table_name="consentconfirmation")
    op.drop_index(op.f("ix_consentconfirmation_post_id"), table_name="consentconfirmation")
    op.drop_table("consentconfirmation")
    op.drop_index(op.f("ix_usersession_value"), table_name="usersession")
    op.drop_index(op.f("ix_usersession_user_id"), table_name="usersession")
    op.drop_index(op.f("ix_usersession_revoked_at"), table_name="usersession")
    op.drop_index(op.f("ix_usersession_expires_at"), table_name="usersession")
    op.drop_table("usersession")
    op.drop_index(op.f("ix_report_target_type"), table_name="report")
    op.drop_index(op.f("ix_report_target_id"), table_name="report")
    op.drop_index(op.f("ix_report_status"), table_name="report")
    op.drop_index(op.f("ix_report_reporter_user_id"), table_name="report")
    op.drop_index(op.f("ix_report_reason"), table_name="report")
    op.drop_index(op.f("ix_report_created_at"), table_name="report")
    op.drop_table("report")
    op.drop_index(op.f("ix_profileview_viewer_user_id"), table_name="profileview")
    op.drop_index(op.f("ix_profileview_viewed_user_id"), table_name="profileview")
    op.drop_index(op.f("ix_profileview_viewed_at"), table_name="profileview")
    op.drop_table("profileview")
    op.drop_index(op.f("ix_profile_user_id"), table_name="profile")
    op.drop_index(op.f("ix_profile_slug"), table_name="profile")
    op.drop_table("profile")
    op.drop_index(op.f("ix_mediapost_user_id"), table_name="mediapost")
    op.drop_index(op.f("ix_mediapost_status"), table_name="mediapost")
    op.drop_index(op.f("ix_mediapost_created_at"), table_name="mediapost")
    op.drop_table("mediapost")
    op.drop_index(op.f("ix_conversation_user_b_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_user_a_id"), table_name="conversation")
    op.drop_index(op.f("ix_conversation_status"), table_name="conversation")
    op.drop_table("conversation")
    op.drop_index(op.f("ix_auditlog_entity_type"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_entity_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_created_at"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_actor_user_id"), table_name="auditlog")
    op.drop_index(op.f("ix_auditlog_action"), table_name="auditlog")
    op.drop_table("auditlog")
    op.drop_index(op.f("ix_accounttoken_user_id"), table_name="accounttoken")
    op.drop_index(op.f("ix_accounttoken_used_at"), table_name="accounttoken")
    op.drop_index(op.f("ix_accounttoken_token_hash"), table_name="accounttoken")
    op.drop_index(op.f("ix_accounttoken_purpose"), table_name="accounttoken")
    op.drop_index(op.f("ix_accounttoken_expires_at"), table_name="accounttoken")
    op.drop_table("accounttoken")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
